/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_irQwh9CQH",
        "userPoolWebClientId": "7tg4nkkco2hljjudoem8cv0aql",
        "mandatorySignIn": false
    }
};


export default awsmobile;
