/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_RI8XBDcog",
        "userPoolWebClientId": "a2tsigds7ok4ah53osi8tn2vf",
        "mandatorySignIn": false
    }
};


export default awsmobile;
